ev3_backend/ev3_backend/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from app import views as v

urlpatterns = [
    # USER GENERAL
    path("", v.inicio, name="inicio"),
    path("login/", v.login, name="login"),
    path("logout/", v.Logout, name="logout"),
    path("register/", v.Register, name="register"),
    
    # CARRO
    path("carro/", v.RenderCarro, name="carro"),
    path("carro/add/<int:id>/", v.AddCarro, name="addCarro"),
    path("carro/add/<int:id>/<str:op>/", v.CantidadCarro, name="cantCarro"),
    path("carro/delete/<int:id>/", v.DeleteItemCarro, name="deleteCarro"),
    path("carro/sale/", v.Vender, name="vender"),

    # ADMIN
    path("admin/admin-dashboard/", v.AdminDashboard, name="admin-dashboard"),

    # CATEGORIAS
    path("admin/categorias/", v.RenderCategorias, name="categorias"), 
    path("admin/categorias/eliminar-categorias<int:id>", v.EliminarCategoria, name="eliminar-categorias"),
    path("admin/categorias/actualizar-categorias<int:id>", v.ActualizarCategoria, name="actualizar-categorias"),
    
    # PRODUCTOS
    path("admin/productos/", v.RenderProductos, name="productos"), 
    path("admin/productos/eliminar-productos<int:id>", v.EliminarProducto, name="eliminar-productos"),
    path("admin/productos/actualizar-productos<int:id>", v.ActualizarProducto, name="actualizar-productos"),
    path("admin/productos/descriptor/<int:id>/", v.RenderDesc, name="descriptor"),

    # Ventas
    path("admin/ventas/", v.RenderVentas, name="ventas"), 
    path("admin/ventas/eliminar-venta<int:id>", v.EliminarVenta, name="eliminar-venta"),
    path("admin/ventas/detalle-venta<int:id>", v.RenderDetalleVenta, name="detalle-venta"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ev3_backend/app/models.py
from django.db import models
from django.contrib.auth.hashers import make_password, check_password

# USERS
class Rol(models.Model):
    nombre = models.CharField(max_length=20, default='')

class User(models.Model):
    nombre = models.CharField(max_length=30, default='')
    username = models.CharField(max_length=30, default='', unique=True)
    password = models.CharField(max_length=128, default='')
    rol = models.ForeignKey(Rol, on_delete=models.DO_NOTHING, default=1)

    def set_password(self, raw_password):
        self.password = make_password(raw_password)

    def check_password(self, raw_password):
        return check_password(raw_password, self.password)

# PRODUCTOS
class Categoria(models.Model):
    nombre = models.CharField(max_length=20, default='', unique=True)
    disponible = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre  

class Producto(models.Model):
    nombre = models.CharField(max_length=30, default='', unique=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)
    stock = models.IntegerField()
    precio_unitario = models.FloatField()
    imagen = models.ImageField(upload_to='productos/', null=True, blank=True)
    descripcion = models.TextField(default='')
    disponible = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre  

# VENTA
class Venta(models.Model):
    fecha = models.DateField()
    total = models.FloatField()
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    estado = models.BooleanField(default=True)

class DetalleVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.DO_NOTHING)
    producto = models.ForeignKey(Producto, on_delete=models.DO_NOTHING)
    precio_momento_venta = models.FloatField(default=0)
    cantidad = models.IntegerField(default=1)
    subtotal = models.FloatField()

ev3_backend/templates/shared/crear.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Crear{% endblock title %}


{% block content %}
<body>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">
            {% if form.nombre.value %}
            Actualizar
            {% else %}
            Guardar
            {% endif %}
        </button>
    </form>
</body>
{% endblock %}

ev3_backend/templates/shared/inicio.html
{% extends 'base.html' %} {% load static %} 
{% block title %}Inicio{% endblock %} 
{% block content %}

<nav class="navbar navbar-expand-xl bg-dark w-100">
    <div class="container-fluid">
        <a href="{% url 'inicio' %}" class="navbar-brand">
          <img src="{% static 'images/icon/logo.png' %}" style="width: 100px" />
        </a>
        {% if user_id %}
        <div class="col ms-5">
            <p style="color: white;">Hola:</p>
            <p style="color: white;">{{ nombre }}</p>
        </div>
        {% else %}
        <div class="col ms-5">
            <p style="color: white;">Bienvenido</p>
        </div>
        {% endif %}
      <form class="d-flex ms-auto" role="search" method="POST">
        {% csrf_token %}
        <input
          class="form-control me-2"
          type="search"
          placeholder="Search"
          aria-label="Search"
          name="search"
        />
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
      <a href="{% url 'carro' %}" class="btn btn-success ms-4"
        ><i class="fa-solid fa-cart-shopping"></i>
      </a>
      {% if not user_id %}
      <a href="{% url 'login' %}" class="btn btn-primary ms-2"
        ><i class="fa-solid fa-user"></i>
      </a>
      {% else %}
        {% if rol_user == 2 %}
        <a href="{% url 'admin-dashboard' %}" class="btn btn-primary ms-2">
            <i class="fa-solid fa-user-tie"></i>
        </a>
        {% endif %}
      <a href="{% url 'logout' %}" class="btn btn-danger ms-2"
        ><i class="fa-solid fa-right-from-bracket"></i>
      </a>
      {% endif %}
    </div>
</nav>

<div class="container mt-5">
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <div class="alert alert-success">
                    <p>{{ message }}</p>
                </div>
                {% elif message.tags == 'error' %}
                <div class="alert alert-danger">
                    <p>{{ message }}</p>
                </div>
                {% elif message.tags == 'info' %}
                <div class="alert alert-info">
                    <p>{{ message }}</p>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'images/carousel/ropa.jpg' %}" class="d-block w-100" alt="Imagen 1" style="max-height: 25rem;">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Ropa</h5>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/carousel/juguetes.jpg' %}" class="d-block w-100" alt="Imagen 2" style="max-height: 25rem;">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Juguetes</h5>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/carousel/muebles.jfif' %}" class="d-block w-100" alt="Imagen 3" style="max-height: 25rem;">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Muebles</h5>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Anterior</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Siguiente</span>
        </button>
    </div>
</div>

<section class="catalog-container py-5">
    <h1>Catalogo Completo</h1>
    {% if categorias %}
    <div class="row">
        {% for cate in categorias %}
        <h2 class="h2" style="border-bottom: solid;">{{ cate.nombre }}</h2>
        <div class="col">
            <div class="d-flex overflow-auto flex-nowrap">
                {% for i in cate.producto_set.all %}
                <div class="card mx-2 shadow-lg">
                    <div class="card-body text-center">
                        {% if i.imagen %}
                        <a href="{% url 'descriptor' i.id %}">
                            <img 
                            src="{{ i.imagen.url }}" 
                            alt="{{ i.nombre }}" 
                            class="img-fluid" 
                            style="max-height: 100px; max-width: 100px;"
                            >
                        </a>
                        {% else %}
                        <p class="text-danger">No hay imagen</p>
                        {% endif %}
                    </div>
                    <div class="card-footer text-center">
                        <p class="card-title mb-0">{{ i.nombre }}</p>
                        <p class="card-title mb-0 text-success">Valor: {{ i.precio_unitario|floatformat:0 }}</p>
                        <p class="card-title mb-0">Stock: {{ i.stock }}</p>
                    </div>
                    
                    <div class="mx-2 py-2">
                        <form method="POST" action="{% url 'addCarro' i.id %}">
                            {% csrf_token %}
                            <div class="d-flex justify-content-center align-items-center">
                                <input type="number" name="cantidad" min="1" max="{{ i.stock }}" value="1" class="form-control mt-2" style="max-width: 80px;">
                                <button type="submit" class="btn btn-success mt-2 ms-2" style="width: 120px; border-radius: 5px; font-weight: bold;">
                                    <i class="fa-solid fa-cart-plus"></i>
                                </button>
                            </div>
                        </form>
                    </div>
                 </div>
                 {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <h5>NADA AUN</h5>
    {% endif %}
</section>

{% endblock content %}

ev3_backend/templates/shared/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block content %}

<div class="navbar navbar-expand-xl bg-dark w-100">
    <a href="{% url 'inicio' %}" class="navbar-brand">
        <img src="{% static 'images/icon/logo.png' %}" style="width: 100px" />
    </a>
</div>

<div class="container d-flex align-items-center justify-content-center" style="height: 70vh;">
    <div class="card p-4 shadow" style="max-width: 32rem; width: 100%;">
        <form method="POST">
            {% csrf_token %}
            <h1 class="card-title text-center">Inicio de Sesión</h1>

            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <div class="alert alert-success">
                        <p>{{ message }}</p>
                    </div>
                    {% elif message.tags == 'error' %}
                    <div class="alert alert-danger">
                        <p>{{ message }}</p>
                    </div>
                    {% endif %}
                {% endfor %}
            {% endif %}

            <div class="form-group mt-3">
                <label for="{{ form.username.id_for_label }}" class="form-label">Nombre de Usuario</label>
                <div class="input-group">
                    {{ form.username }}
                </div>
            </div>

            <div class="form-group mt-2">
                <label for="{{ form.password.id_for_label }}" class="form-label">Contraseña</label>
                {{ form.password }}
            </div>

            <button type="submit" class="btn btn-secondary w-100 mt-3">LogIn</button>
        </form>
        <p class="text-center mt-3">¿No tienes cuenta? <a href="{% url 'register' %}">Regístrate aquí</a></p>
    </div>
</div>

{% endblock content %}

ev3_backend/templates/shared/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="navbar navbar-expand-xl bg-dark w-100">
    <a href="{% url 'inicio' %}" class="navbar-brand">
        <img src="{% static 'images/icon/logo.png' %}" style="width: 100px" />
    </a>
</div>
<div class="container d-flex align-items-center justify-content-center" style="height: 70vh;">
    <div class="card p-4 shadow" style="max-width: 32rem; width: 100%;">
        <form method="POST">
            {% csrf_token %}
            <h1 class="card-title text-center">Registro</h1>

            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <div class="alert alert-success">
                        <p>{{ message }}</p>
                    </div>
                    {% elif message.tags == 'error' %}
                    <div class="alert alert-danger">
                        <p>{{ message }}</p>
                    </div>
                    {% else %}
                    <div class="alert alert-info">
                        <p>{{ message }}</p>
                    </div>
                    {% endif %}
                {% endfor %}
            {% endif %}

            <div class="form-group mt-3">
                {{ form.as_p }}
            </div>

            <button type="submit" class="btn btn-secondary w-100 mt-3">Registrar</button>
        </form>
        <p class="text-center mt-3">¿Ya tienes una cuenta? <a href="{% url 'login' %}">Inicia sesión aquí</a></p>
    </div>
</div>
{% endblock %}